name: Nightly Collections Cron

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/cron
        run: |
          curl -s -X POST "${{ secrets.CRON_BASE_URL }}/api/cron" -H 'Content-Type: application/json'

